routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/', function () {
    return view('dashboard/index');
})->name('dashboard');


// Route::get('/table', 'UserController@index')->name('table');
Route::get('/biodata', 'BiodataController@Index')->name('biodata');

Route::resource('member', 'UserController')->names('member');
// ->name('index', 'table')
// ->name('create', 'table.create')
// ->name('store', 'table.store')
// ->name('show', 'table.show')
// ->name('edit', 'table.edit')
// ->name('update', 'table.update')
// ->name('destroy', 'table.destroy');

// auth
Route::get('/login', 'AuthController@login')->name('login');
Route::get('/register', 'AuthController@register')->name('register');

app/Models/Member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'univ', 'asal'];
}

resources/views/member/edit.blade.php
@extends('layout/main')
@section('heading', 'Edit Member')
@section('menu-member', 'active')
@section('content')
    <form>
        <div class="card-body">
            <div class="form-group">
                <label for="name">
                    Nama
                </label>
                <input type="text" class="form-control" id="name" placeholder="Enter email" value="{{ $data['name'] }}"
                    readonly>
            </div>
            <div class="form-group">
                <label for="univ">Asal Universitas</label>
                <input type="text" class="form-control" id="univ" placeholder="univ" readonly
                    value="{{ $data['univ'] ?? '-' }}">
            </div>

            <div class="form-group">
                <label for="univ">Asal Daerah</label>
                <input type="text" class="form-control" id="univ" placeholder="asal" readonly
                    value="{{ $data['asal'] ?? '-' }}">
            </div>

        </div>
        <!-- /.card-body -->
    </form>
@endsection

resources/views/member/index.blade.php
@extends('layout/main')
@section('menu-member', 'active')
@php
    $color = [
        'UAJY' => 'success',
        'UKDW' => 'primary',
        'UPN' => 'danger',
        '' => '',
    ];
@endphp
@section('content')
    <h4>
        Daftar Anggota Bootcamp Batch 9
    </h4>
    <a href="{{ route('member.create') }}" class="btn btn-primary">Tambah Anggota</a>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 10px">#</th>
                <th>Nama</th>
                <th>Asal Universitas</th>
                <th>Asal Daerah</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {{-- @for ($i = 0; $i < count($data); $i++)
                <tr>
                    <td>{{ $i + 1 }}.</td>
                    <td>{{ $data[$i]['nama'] }}</td>
                    <td>{{ $data[$i]['universitas'] }}</td>
                    <td>{{ $data[$i]['daerah'] }}</td>
                </tr>
            @endfor --}}

            @foreach ($data as $value)
                <tr>
                    <td>{{ $loop->iteration }}.</td>
                    <td>{{ $value['name'] }}</td>
                    <td>
                        <span class="badge badge-{{ $color[$value['univ']] }}">{{ $value['univ'] }}</span>
                    </td>
                    <td>{{ $value['asal'] }}</td>
                    <td>
                        <a href="{{ route('member.show', $value['id']) }}" class="btn btn-sm btn-info">Detail</a>
                        <a href="{{ route('member.edit', $value['id']) }}" class="btn btn-sm btn-warning">Edit</a>
                        <form action="{{ route('member.destroy', $value['id']) }}" method="POST" style="display: inline">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                </tr>
            @endforeach

        </tbody>
    </table>
@endsection

resources/views/member/show.blade.php
@extends('layout/main')
@section('heading', $isEdit ? 'Edit Member' : 'Detail Member')
@section('menu-member', 'active')
@section('content')
    <form method="POST" action="{{ $isEdit ? route('member.update', $data['id']) : '#' }}">
        @csrf
        @if ($isEdit)
            @method('PUT')
        @endif
        <input type="hidden" name="id" value="{{ $data['id'] }}">
        <div class="card-body">
            <div class="form-group">
                <label for="name">
                    Nama
                </label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Enter email"
                    value="{{ $data['name'] }}" {{ $isEdit ? '' : 'disabled' }}>

            </div>
            <div class="form-group">
                <label for="univ">Asal Universitas</label>
                <input type="text" class="form-control" name="univ" id="univ" placeholder="univ"
                    value="{{ $data['univ'] ?? '-' }}" {{ $isEdit ? '' : 'disabled' }}>
            </div>

            <div class="form-group">
                <label for="univ">Asal Daerah</label>
                <input type="text" class="form-control" name="asal" id="asal" placeholder="asal"
                    value="{{ $data['asal'] ?? '-' }}" {{ $isEdit ? '' : 'disabled' }}>
            </div>

        </div>
        @if ($isEdit)
            <!-- /.card-body -->
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a type='button' class="btn btn-danger" href="{{ route('member.index') }}">Cancel</a>
            </div>
        @else
            <div class="card-footer">
                <a type='button' class="btn btn-primary" href="{{ route('member.edit', $data['id']) }}">Edit</a>
                <a type='button' class="btn btn-danger" href="{{ route('member.index') }}">Back</a>
            </div>
        @endif
        <!-- /.card-body -->
    </form>
@endsection